name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Instrumented Tests
      uses: ReactiveCircus/android-emulator-runner@v2.12.0
      with:
        api-level: 29
        script: chmod +x gradlew && ./gradlew connectedCheck

