name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Android Emulator Runner (Run Instrumented Tests)
      uses: ReactiveCircus/android-emulator-runner@v2.12.0
      with:
        api-level: 29
        script: chmod +x gradlew &&./gradlew connectedAndroidTest

